# Generated by Django 4.0.4 on 2022-04-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messengerbelayer',
            name='photo',
            field=models.TextField(),
        ),
    ]
